
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.transport;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-12T00:06:04.065+03:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "transport",
                      portName = "transportSOAP",
                      targetNamespace = "http://www.example.org/transport/",
                      wsdlLocation = "http://idu0080.ttu.ee/transport?wsdl",
                      endpointInterface = "org.example.transport.Transport")
                      
public class TransportImpl implements Transport {

    private static final Logger LOG = Logger.getLogger(TransportImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.transport.Transport#transport(java.lang.String  pakkumusId )*
     */
    public java.lang.String transport(java.lang.String pakkumusId) { 
        LOG.info("Executing operation transport");
        System.out.println(pakkumusId);
        try {
            java.lang.String _return = "_return-258516731";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
