
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-23T16:49:40.827+03:00
 * Generated source version: 2.5.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "CourierServiceService",
                      portName = "CourierServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://tund.ttu.ee/orderservice/couriers?wsdl",
                      endpointInterface = "ttu.idu0080.order.server.CourierService")
                      
public class CourierServiceImpl implements CourierService {

    private static final Logger LOG = Logger.getLogger(CourierServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.CourierService#getAllCouriers(*
     */
    public java.util.List<ttu.idu0080.order.server.Courier> getAllCouriers() { 
        LOG.info("Executing operation getAllCouriers");
        try {
            java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
            ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnVal1AddressesVal1.setAddress(-1031396815);
            _returnVal1AddressesVal1.setCountry("Country633974094");
            _returnVal1AddressesVal1.setCounty("County-817022481");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress-1582256798");
            _returnVal1AddressesVal1.setTownVillage("TownVillage-1478750979");
            _returnVal1AddressesVal1.setZipcode("Zipcode-427388699");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(2121104756);
            _returnVal1.setName("Name1069098744");
            _returnVal1.setPercentFromOrder(2065169870);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.CourierService#getCouriersByAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.order.server.Courier> getCouriersByAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getCouriersByAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
            ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnVal1AddressesVal1.setAddress(-639200468);
            _returnVal1AddressesVal1.setCountry("Country-1369739701");
            _returnVal1AddressesVal1.setCounty("County-2048024673");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress1434648041");
            _returnVal1AddressesVal1.setTownVillage("TownVillage1517305877");
            _returnVal1AddressesVal1.setZipcode("Zipcode1879048746");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(-1082750005);
            _returnVal1.setName("Name-1738121664");
            _returnVal1.setPercentFromOrder(1013272539);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.CourierService#getCourierById(int  courierId )*
     */
    public ttu.idu0080.order.server.Courier getCourierById(int courierId) { 
        LOG.info("Executing operation getCourierById");
        System.out.println(courierId);
        try {
            ttu.idu0080.order.server.Courier _return = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnAddressesVal1.setAddress(287725908);
            _returnAddressesVal1.setCountry("Country194261611");
            _returnAddressesVal1.setCounty("County573603077");
            _returnAddressesVal1.setStreetAddress("StreetAddress-195182851");
            _returnAddressesVal1.setTownVillage("TownVillage2143850576");
            _returnAddressesVal1.setZipcode("Zipcode330018450");
            _returnAddresses.add(_returnAddressesVal1);
            _return.getAddresses().addAll(_returnAddresses);
            _return.setEnterprise(1017630847);
            _return.setName("Name-1305615735");
            _return.setPercentFromOrder(451639515);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
