
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-11T23:38:44.062+03:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://tund.ttu.ee:80/orderservice/orders?wsdl",
                      endpointInterface = "ttu.idu0080.order.server.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerId(int  customerId )*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerId(int customerId) { 
        LOG.info("Executing operation getOrdersByCustomerId");
        System.out.println(customerId);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(661805900);
            _returnVal1Customer.setFirstName("FirstName722848800");
            _returnVal1Customer.setLastName("LastName596376248");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1379951387);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(914473453);
            _returnVal1OrderProductsVal1.setPrice(0.3558731f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.24333805f);
            _returnVal1OrderProductsVal1.setProductCount(208852945);
            _returnVal1OrderProductsVal1.setProductName("ProductName-388166976");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.6837486f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1636401669);
            _returnVal1Seller.setName("Name135989903");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(182003264);
            _returnVal1ShippingAddress.setCountry("Country651759074");
            _returnVal1ShippingAddress.setCounty("County-1709619560");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress8520747");
            _returnVal1ShippingAddress.setTownVillage("TownVillage301434904");
            _returnVal1ShippingAddress.setZipcode("Zipcode864093894");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByOrderId(int  orderId )*
     */
    public ttu.idu0080.order.server.Order getOrdersByOrderId(int orderId) { 
        LOG.info("Executing operation getOrdersByOrderId");
        System.out.println(orderId);
        try {
            ttu.idu0080.order.server.Order _return = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnCustomer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnCustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            ttu.idu0080.order.server.Address _returnCustomerAddressesVal1 = new ttu.idu0080.order.server.Address();
            _returnCustomerAddressesVal1.setAddress(388448957);
            _returnCustomerAddressesVal1.setCountry("Country-1906477138");
            _returnCustomerAddressesVal1.setCounty("County-1998379855");
            _returnCustomerAddressesVal1.setStreetAddress("StreetAddress435966868");
            _returnCustomerAddressesVal1.setTownVillage("TownVillage2120572916");
            _returnCustomerAddressesVal1.setZipcode("Zipcode-1155820095");
            _returnCustomerAddresses.add(_returnCustomerAddressesVal1);
            _returnCustomer.getAddresses().addAll(_returnCustomerAddresses);
            _returnCustomer.setCustomer(2126984203);
            _returnCustomer.setFirstName("FirstName-1045359439");
            _returnCustomer.setLastName("LastName431821937");
            _return.setCustomer(_returnCustomer);
            _return.setOrderId(1185750165);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnOrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnOrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnOrderProductsVal1.setOrderProduct(651087312);
            _returnOrderProductsVal1.setPrice(0.49390727f);
            _returnOrderProductsVal1.setPriceTotal(0.8369016f);
            _returnOrderProductsVal1.setProductCount(-49937914);
            _returnOrderProductsVal1.setProductName("ProductName-369511770");
            _returnOrderProducts.add(_returnOrderProductsVal1);
            _return.getOrderProducts().addAll(_returnOrderProducts);
            _return.setPriceTotal(0.27494973f);
            ttu.idu0080.order.server.Seller _returnSeller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnSellerAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnSellerAddressesVal1.setAddress(1942467621);
            _returnSellerAddressesVal1.setCountry("Country486284286");
            _returnSellerAddressesVal1.setCounty("County862181060");
            _returnSellerAddressesVal1.setStreetAddress("StreetAddress191734056");
            _returnSellerAddressesVal1.setTownVillage("TownVillage557807984");
            _returnSellerAddressesVal1.setZipcode("Zipcode985492247");
            _returnSellerAddresses.add(_returnSellerAddressesVal1);
            _returnSeller.getAddresses().addAll(_returnSellerAddresses);
            _returnSeller.setEnterprise(719487432);
            _returnSeller.setName("Name-1977476166");
            _return.setSeller(_returnSeller);
            ttu.idu0080.order.server.Address _returnShippingAddress = new ttu.idu0080.order.server.Address();
            _returnShippingAddress.setAddress(701267666);
            _returnShippingAddress.setCountry("Country1066265476");
            _returnShippingAddress.setCounty("County1823676358");
            _returnShippingAddress.setStreetAddress("StreetAddress1044540953");
            _returnShippingAddress.setTownVillage("TownVillage-1763889630");
            _returnShippingAddress.setZipcode("Zipcode-1189670863");
            _return.setShippingAddress(_returnShippingAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getAllOrders(*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getAllOrders() { 
        LOG.info("Executing operation getAllOrders");
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-198910044);
            _returnVal1Customer.setFirstName("FirstName-2102823799");
            _returnVal1Customer.setLastName("LastName-2130052123");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-2104407001);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(-739747164);
            _returnVal1OrderProductsVal1.setPrice(0.4070171f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.6622941f);
            _returnVal1OrderProductsVal1.setProductCount(-2085466571);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1102839487");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.0049297214f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1186936765);
            _returnVal1Seller.setName("Name1120981708");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(-1558742721);
            _returnVal1ShippingAddress.setCountry("Country-1104075701");
            _returnVal1ShippingAddress.setCounty("County1259302366");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-212258774");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-158099203");
            _returnVal1ShippingAddress.setZipcode("Zipcode-972571847");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByShippingAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByShippingAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getOrdersByShippingAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-434901456);
            _returnVal1Customer.setFirstName("FirstName2109472955");
            _returnVal1Customer.setLastName("LastName1260309517");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1080827854);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1453983537);
            _returnVal1OrderProductsVal1.setPrice(0.3620996f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.3760174f);
            _returnVal1OrderProductsVal1.setProductCount(1278433252);
            _returnVal1OrderProductsVal1.setProductName("ProductName300647686");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.60661197f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1224272024);
            _returnVal1Seller.setName("Name419777346");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(-1323918160);
            _returnVal1ShippingAddress.setCountry("Country1776797109");
            _returnVal1ShippingAddress.setCounty("County-763707936");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress939483967");
            _returnVal1ShippingAddress.setTownVillage("TownVillage1730991741");
            _returnVal1ShippingAddress.setZipcode("Zipcode-1266780022");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerLastName(java.lang.String  lastName )*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerLastName(java.lang.String lastName) { 
        LOG.info("Executing operation getOrdersByCustomerLastName");
        System.out.println(lastName);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(1930932220);
            _returnVal1Customer.setFirstName("FirstName-1051566888");
            _returnVal1Customer.setLastName("LastName24226752");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1809847669);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(600653026);
            _returnVal1OrderProductsVal1.setPrice(0.16682965f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.7003295f);
            _returnVal1OrderProductsVal1.setProductCount(-142663826);
            _returnVal1OrderProductsVal1.setProductName("ProductName413314413");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.42919052f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1635728381);
            _returnVal1Seller.setName("Name737322706");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(543773368);
            _returnVal1ShippingAddress.setCountry("Country-437568253");
            _returnVal1ShippingAddress.setCounty("County2047461248");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress681330852");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-307051345");
            _returnVal1ShippingAddress.setZipcode("Zipcode-1529312734");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
