package org.example.transport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-12T00:03:47.931+03:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "transport", 
                  wsdlLocation = "http://idu0080.ttu.ee/transport?wsdl",
                  targetNamespace = "http://www.example.org/transport/") 
public class Transport_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/transport/", "transport");
    public final static QName TransportSOAP = new QName("http://www.example.org/transport/", "transportSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://idu0080.ttu.ee/transport?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Transport_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://idu0080.ttu.ee/transport?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Transport_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Transport_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Transport_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Transport
     */
    @WebEndpoint(name = "transportSOAP")
    public Transport getTransportSOAP() {
        return super.getPort(TransportSOAP, Transport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Transport
     */
    @WebEndpoint(name = "transportSOAP")
    public Transport getTransportSOAP(WebServiceFeature... features) {
        return super.getPort(TransportSOAP, Transport.class, features);
    }

}
