
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-11T23:43:03.946+03:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "CourierServiceService",
                      portName = "CourierServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://tund.ttu.ee:80/orderservice/couriers?wsdl",
                      endpointInterface = "ttu.idu0080.order.server.CourierService")
                      
public class CourierServiceImpl implements CourierService {

    private static final Logger LOG = Logger.getLogger(CourierServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.CourierService#getAllCouriers(*
     */
    public java.util.List<ttu.idu0080.order.server.Courier> getAllCouriers() { 
        LOG.info("Executing operation getAllCouriers");
        try {
            java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
            ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnVal1AddressesVal1.setAddress(-296185231);
            _returnVal1AddressesVal1.setCountry("Country458779033");
            _returnVal1AddressesVal1.setCounty("County-2053717667");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress-1484244866");
            _returnVal1AddressesVal1.setTownVillage("TownVillage53363321");
            _returnVal1AddressesVal1.setZipcode("Zipcode-2114345129");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(1035252922);
            _returnVal1.setName("Name-500667280");
            _returnVal1.setPercentFromOrder(1087992516);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.CourierService#getCouriersByAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.order.server.Courier> getCouriersByAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getCouriersByAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
            ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnVal1AddressesVal1.setAddress(-86293579);
            _returnVal1AddressesVal1.setCountry("Country-2125574179");
            _returnVal1AddressesVal1.setCounty("County2034225358");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress-2039848232");
            _returnVal1AddressesVal1.setTownVillage("TownVillage-1744059390");
            _returnVal1AddressesVal1.setZipcode("Zipcode1149792195");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(918656752);
            _returnVal1.setName("Name1449992807");
            _returnVal1.setPercentFromOrder(803036826);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.CourierService#getCourierById(int  courierId )*
     */
    public ttu.idu0080.order.server.Courier getCourierById(int courierId) { 
        LOG.info("Executing operation getCourierById");
        System.out.println(courierId);
        try {
            ttu.idu0080.order.server.Courier _return = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnAddressesVal1.setAddress(1877602006);
            _returnAddressesVal1.setCountry("Country-597216679");
            _returnAddressesVal1.setCounty("County-1262689633");
            _returnAddressesVal1.setStreetAddress("StreetAddress2086736815");
            _returnAddressesVal1.setTownVillage("TownVillage-1397405602");
            _returnAddressesVal1.setZipcode("Zipcode-173725414");
            _returnAddresses.add(_returnAddressesVal1);
            _return.getAddresses().addAll(_returnAddresses);
            _return.setEnterprise(1395296448);
            _return.setName("Name1047793228");
            _return.setPercentFromOrder(1047822135);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
