
package org.example.transport;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-12T00:03:47.927+03:00
 * Generated source version: 2.7.4
 * 
 */
 
public class Transport_TransportSOAP_Server{

    protected Transport_TransportSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new TransportImpl();
        String address = "http://idu0080.ttu.ee/transport";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Transport_TransportSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
