package ee.ttu.tud.idu0080.bp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-11T23:34:23.258+03:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "bp", 
                  wsdlLocation = "http://localhost:8085/BpService?wsdl",
                  targetNamespace = "http://idu0080.tud.ttu.ee/bp/") 
public class Bp_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://idu0080.tud.ttu.ee/bp/", "bp");
    public final static QName BpSOAP = new QName("http://idu0080.tud.ttu.ee/bp/", "bpSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8085/BpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Bp_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8085/BpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Bp_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Bp_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bp_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Bp
     */
    @WebEndpoint(name = "bpSOAP")
    public Bp getBpSOAP() {
        return super.getPort(BpSOAP, Bp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Bp
     */
    @WebEndpoint(name = "bpSOAP")
    public Bp getBpSOAP(WebServiceFeature... features) {
        return super.getPort(BpSOAP, Bp.class, features);
    }

}
